version: '3.8'
services:
  docker-test:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=React
    ports:
      - "3200:80"
    env_file:
      - ./.env
    container_name: nextgen-cont
    image: nextgen-img
    