version: '3.3'
services:
 nextgen-client:
  build:
   context: .
   dockerfile: Dockerfile.dev
  ports:
   - "3501:3501"
  env_file:
   - ./.env
  container_name: nextgen-client-cont
  image: nextgen-client-img